import ToastProvider from "@/components/providers/ToastProvider";
import {
  ClerkProvider
} from "@clerk/nextjs";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import "@uploadthing/react/styles.css";
import type { Metadata } from "next";
import { Signika_Negative } from "next/font/google";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import "./globals.css";

const inter = Signika_Negative({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Alpha Vision",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <ToastProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
