import type { Metadata } from "next"
import { Inter, Signika_Negative } from "next/font/google"
import "./globals.css"
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs"
import ToastProvider from "@/components/providers/ToastProvider"

const inter = Signika_Negative({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Alpha Vision",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToastProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
